travis:
  secure:
    BINSTAR_TOKEN: YSPI+NiGikgddLccRmbi7AJUaBj21Y5zb3lTgS/Xqo/NEITrCvoT0A648QgmjlXKAmo6wwt3Dy2LtNQDpDHxcdUtxGw6yTERt9k+6aFKDbBYRic6miFnBvoa2WRFE62nMV7ckUYoM5Cpw/UPJ8tosD/AZcNYEXHwj4SU2zsLuKuvUMKdJ4Y2tdRRie0lytFGQ92JQj/jyNUJWfckJYPfcViYQdfhfpSvJ6kV2ToTBleT7ibk5FKe4+MbfOWt+Dx19cQ5I1vjuPIdbTL+lSNQZEYSM1JBx8y/mikDO675udoapD0mE1QUNeMrobktF+kwl6rVbsWYAP/r/u012IKtwCAGGoAl3f6C3dkOMbV8xMCV7m7HyeheGpSW6LtWDNdvmMxDqpOphIDcaZTM3Zrhlq/Hmwkyby79fDfScm7UgtvfeCCcHE+bXquEpBFADECGYlyKEMwswwCttttW7OcvMskUAcJmyYLiAcEu2M3Sy2yRGSxrOJAM7RWgps8aryRt9Noi7SwtxoMknNIxDkNQbNgSaZ60xlmQDdn8fhyzBh2jbDCUCf0+G4tN3r71kjX81W4Ebw/om0sPPhiE1RbxuEigTqY7JUCSp82cn5lMaKIV8Oe1rakGCPmHDCZr/Vi0pLgAvlkAdWkZC8xoMboxZaqIr/susEJc2kUDs0H7wtM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
